### ISSUE TITLE
Refactor DraggableBox / GNodeSkin

### ISSUE THREAD

**Issue by eckig** [tesis-dynaware/graph-editor#2]
Essentially the GNodeSkin consists (mainly) of a DraggableBox so it is about both of them.

I would like to suggest to refactor the DraggableBox to extend Region instead of StackPane.
It is not a very good idea to stack multiple layers on top of each other just to achieve some borders. The number of Nodes (JavaFX) in the SceneGraph should be kept as low as possible.

With CSS and the Regions css-property "-fx-background-color" you can stack multiple colors on top of each other to get multiple borders and/or background colors, I stamped together a little example replicating the look of a default JavaFX button for a Region:

SSCE:

``` java
public class Main extends Application {
    @Override
    public void start(Stage primaryStage) {
        BorderPane root = new BorderPane();

        Region draggableBox = new Region();
        draggableBox.setMaxSize(150, 90);
        draggableBox.resize(150, 90);
        draggableBox.getStyleClass().add("draggable-box");

        root.setTop(new Button("Test"));
        root.setCenter(draggableBox);

        Scene scene = new Scene(root,400,400);
        scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

and the CSS for the Region:

``` CSS
.draggable-box {
    -fx-background-color: -fx-outer-border, -fx-inner-border, -fx-body-color;
    -fx-background-insets: 0, 1, 2;
    -fx-background-radius: 3, 3, 2, 1;
    -fx-padding: 4 8 4 8;
}
```

And another feature request: If you add this (or I may create a pull request), please expose the width and height properties of this Region to the GNodeSkin to make custom layouting easier with bindings.
